server:
  port: 8080

app: 
  base-url: http://localhost:8080

spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-authentication
            client-secret: ${CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/oauth2